# Generated by Django 3.1 on 2020-08-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='images',
            field=models.ManyToManyField(to='listings.Photo'),
        ),
    ]
