# Generated by Django 3.1 on 2020-08-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='images',
        ),
    ]
